spring.application.name=Project1Films
spring.datasource.url=jdbc:postgresql://localhost:5432/Films
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/project1films